### ISSUE TITLE
Results for shows should be by any of the matching serviceProviders

### ISSUE THREAD

**Issue by prabhuomkar** [prabhuomkar/frisky#8]
**Bug**:
Query 1:
```
query {
  shows(where: {
    serviceProviders: ["amazonPrime"]
  }) {
    name
  }
}
```
Query 2:
```
query {
  shows(where: {
    serviceProviders: ["netflix", "amazonPrime"]
  }) {
    name
  }
}
```

Query 1 does not show results of Amazon Prime as it only checks for serviceProviders to be ["amazonPrime"] only and collections with ["xyz", "amazonPrime"] are not shown.

**Expected Fix**:
In where: {serviceProviders: []} do the following:
- Check for that each provider in serviceProviders list as $in in MongoDB query 
e.x. for Query 2 all the shows which contain netflix or amazonPrime should be shown.

In a gist: Change the logic of AND to OR for serviceProviders by using $in of MongoDB

**Comment by Swap76** [comment]
@prabhuomkar I will fix this
